### ISSUE TITLE
Obsolete

### ISSUE THREAD

**Issue by AestheticCode** [Draugr-official/Skully#2]
This project is obsolete, native AOT kicks ass.

**Comment by Draugr-official** [comment]
Dotnet native brings issues, like packing the .net framework into the executeable, making the output files massive, that me and others would like to not see.

This project is by no means a replacement, but rather a project that could grow into something bigger. This aims to solve the problems Microsoft are yet to solve issues like retaining a lot of .NET Framework, Roslyn-like architecture in their native compiler.

Fyi: this project is open to contributions.
